FROM python:3.10

LABEL Name="Django-WebApp" Version=1.4.2
LABEL org.opencontainers.image.source = "https://github.com/surasravan/Django-WebApp.git"

ARG srcDir=src
WORKDIR /app
COPY $srcDir/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY $srcDir/run.py .
COPY $srcDir/app ./app

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "run:app"]
